-- Oracle 12c 以降で利用可能な MERGE + RETURNING パターン
-- UPDATE したレコードを SELECT のように表示する

MERGE INTO DB_SAM.TABLE_A tgt
USING (
    SELECT KEY_F, KEY_S, KEY_T, STATUS, RETRY_LIMIT_DATE
    FROM DB_SAM.TABLE_A
    WHERE STATUS IN ('002', '004', '006', '101', '102')
      AND RETRY_END_DATE IS NULL
      AND RETRY_LIMIT_DATE BETWEEN TO_DATE('2026/07/23 16:00:00', 'YYYY/MM/DD HH24:MI:SS')
                               AND TO_DATE('2026/07/23 21:00:00', 'YYYY/MM/DD HH24:MI:SS')
) src
ON (tgt.KEY_F = src.KEY_F AND tgt.KEY_S = src.KEY_S AND tgt.KEY_T = src.KEY_T)
WHEN MATCHED THEN UPDATE SET RETRY_LIMIT_DATE = src.RETRY_LIMIT_DATE + 1
RETURNING KEY_F, KEY_S, KEY_T, STATUS, RETRY_LIMIT_DATE;

-- 補足:
-- - RETURNING句で更新後の値がSELECTのように表示される（SQL*Plus 12c以降）
-- - COMMIT文を明示的に発行するまで未確定。必要に応じて COMMIT; または ROLLBACK; を実行する。
